version: "3"
services:
  api:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/usr/app/
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: "mongo:4"
    ports:
      - "27020:27017"